version: '3.8'

services:
  # 1. 우리 FastAPI 서버
  backend:
    container_name: baebulook-app
    # build: .  <-- 이 줄을 지우거나 #으로 주석 처리하세요!
    image: jeongtaekim97/matzip-backend:latest  # <-- 방금 올린 이미지 주소 입력
    restart: always
    env_file:
      - .env
    expose:
      - "8000"

  # 2. Nginx + SSL 관리자 (초보자 강추)
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'      # 웹 접속
      - '443:443'    # HTTPS 접속
      - '81:81'      # 관리자 페이지 (나중에 보안 위해 닫거나 비번 걸어야 함)
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - backend